name: .NET Build and Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Change to windows-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Adjust based on your project

      - name: Restore Dependencies
        run: dotnet restore WebAppWithDatabase.sln

      - name: Build Solution
        run: dotnet build WebAppWithDatabase.sln --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish WebAppWithDatabase.sln --configuration Release --output ./publish --no-build

      - name: Upload Published Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish
